# version: 1.0.0

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """
$singularity\
$kubernetes\
$pijul_channel\
$docker_context\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$azure\
$battery\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[▲](bold #d79921)"
error_symbol = "[△](#cc241d)"
vimcmd_symbol = "[■](dimmed #98971a)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = '#98971a'

[sudo]
format = "[$symbol]($style)"
style = "bold #b16286"
symbol = "⋈┈"
disabled = false

[username]
style_user = "#d79921 bold"
style_root = "#b16286 bold"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "□ "
read_only = " ◈"
use_os_path_sep = true
style = "#458588"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold #458588'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold #83a598)'

[cmd_duration]
format = "[◄ $duration ](#ebdbb2)"

[jobs]
format = "[$symbol$number]($style) "
style = "#ebdbb2"
symbol = "[▶](#458588)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold #b16286)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed #928374"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](bold #98971a)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "bold #cc241d"

[[battery.display]]
threshold = 60
style = "dimmed #b16286"

[[battery.display]]
threshold = 70
style = "dimmed #d79921"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[△](bold #83a598)"
style = "#83a598"
truncation_symbol = "⋯"
truncation_length = 21
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'dimmed #98971a'
deleted_style = 'dimmed #cc241d'
ignore_submodules = true
disabled = false

[git_status]
style = "bold #83a598"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](#d3869b)"
ahead = "[▴│[${count}](bold #ebdbb2)│](#98971a)"
behind = "[▿│[${count}](bold #ebdbb2)│](#cc241d)"
diverged = "[◇ ▴┤[${ahead_count}](regular #ebdbb2)│▿┤[${behind_count}](regular #ebdbb2)│](#d3869b)"
untracked = "[◌◦](#d79921)"
stashed = "[◃◈](#ebdbb2)"
modified = "[●◦](#d79921)"
staged = "[▪┤[$count](bold #ebdbb2)│](#689d6a)"
renamed = "[◎◦](#83a598)"
deleted = "[✕](#cc241d)"

[deno]
format = " deno [∫ $version](#98971a bold)"
version_format = "${raw}"

[lua]
format = " lua [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold #d79921"

[nodejs]
format = " node [◫ ($version)](bold #b8bb26)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " py [${symbol}${version}]($style)"
symbol = "[⌉](bold #83a598)⌊ "
version_format = "${raw}"
style = "bold #d79921"

[ruby]
format = " rb [${symbol}${version}]($style)"
symbol = "◆ "
version_format = "${raw}"
style = "bold #cc241d"

[rust]
format = " rs [$symbol$version]($style)"
symbol = "⊃ "
version_format = "${raw}"
style = "bold #d65d0e"

[package]
format = " pkg [$symbol$version]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "dimmed #d79921 bold"

[swift]
format = " sw [${symbol}${version}]($style)"
symbol = "◁ "
style = "bold #fb4934"
version_format = "${raw}"

[aws]
disabled = true
format = " aws [$symbol $profile $region]($style)"
style = "bold #458588"
symbol = "▲ "

[buf]
symbol = "■ "
format = " buf [$symbol $version $buf_version]($style)"

[c]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"

[cpp]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = "◯ "
format = " conda [$symbol$environment]($style)"

[pixi]
symbol = "■ "
format = " pixi [$symbol$version ($environment )]($style)"

[dart]
symbol = "◁◅ "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = "◧ "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = "△ "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = "◩ "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = "∩ "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = "❯λ "
format = " hs [$symbol($version )]($style)"

[java]
symbol = "∪ "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = "◎ "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "▪▫▪ "
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = "▴▲▴ "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = 'bold dimmed blue'
symbol = '✶'
format = '[$symbol nix⎪$state⎪]($style) [$name](dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"
